package edu.poly.common;

public enum PageType {
	USER_MANAGEMENT_PAGE, REPORT_MANAGEMENT_PAGE, VIDEO_MANAGEMENT_PAGE,
	SITE_HOME_PAGE, SITE_LOGIN_PAGE, SITE_REGISTRATION_PAGE, SITE_CHANGE_PASSWORD_PAGE, 
	SITE_FORGOT_PASSWORD_PAGE, SITE_EDIT_PROFILE_PAGE, VIDEOS_SHARE_PAGE, VIDEOS_FAVORITE_PAGE,
	VIDEOS_DETAIL_PAGE
}
